from enum import StrEnum


class ErrorCode(StrEnum):
    # Auth
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    UNAUTHORIZED = "UNAUTHORIZED"
    REFRESH_TOKEN_REVOKED = "REFRESH_TOKEN_REVOKED"
    USER_INACTIVE = "USER_INACTIVE"

    # Authorization
    FORBIDDEN = "FORBIDDEN"

    # Resources
    NOT_FOUND = "NOT_FOUND"

    # Storage / quota
    QUOTA_EXCEEDED = "QUOTA_EXCEEDED"

    # Validation
    VALIDATION_ERROR = "VALIDATION_ERROR"

    # Drive / Storage
    NAME_CONFLICT = "NAME_CONFLICT"
    INVALID_OPERATION = "INVALID_OPERATION"
    ITEM_CONTENT_NOT_FOUND = "ITEM_CONTENT_NOT_FOUND"

    # Assistant
    ASSISTANT_UNAVAILABLE = "ASSISTANT_UNAVAILABLE"

    # Generic
    INTERNAL_ERROR = "INTERNAL_ERROR"
